- otto_connector/src/otto_connector/connector.py
- otto_connector/src/otto_connector/robot.py
- otto_connector/src/otto_connector/values.py
- otto_connector/src/otto_connector/wamp_client.py
Modified `WampClient._handle_states_event()` to handle state events properly. It now maintains and publishes a list of all current subsystem sates and a dictionary of active state records, and also handles online/offline status changes properly.
Logs of the connector handling state data:
```
DEBUG:WampClient:Message `all` received from topic v2.robots.states
DEBUG:WampClient:    args: ([{'created': '2023-09-13T01:04:54.680621Z', 'robot': 'a2ea35a5-f87e-4bd0-a335-3fc730f2956b', 'id': '03837121-82f2-46ad-9651-9ec4f70f0847', 'priority': 190, 'sub_system_state': 'SLOW', 'system_state': 'RUN'}, {'created': '2023-09-13T15:43:23.915910Z', 'robot': 'a2ea35a5-f87e-4bd0-a335-3fc730f2956b', 'id': 'bffa22db-dd9b-47e1-9668-db3fcbadebc0', 'priority': 180, 'sub_system_state': 'STARVED', 'system_state': …
```
> Handle state messages

- otto_connector/README.md
- otto_connector/cac_examples/actions.yaml
- otto_connector/src/otto_connector/connector.py
- otto_connector/src/otto_connector/http_client.py
🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
Add support for cancelling all open missions in the system.
The action creates a thread that queries all missions in every state but `SUCCEDED`, `CANCELLING` and `CANCEL`, and excecutes `HTTPClient.cancel_mission()` for each one of them.
https://github.com/inorbit-ai/inorbit-robot-connectors/assets/41840767/f21c0fc8-26b3-48cb-9550-9055cc56b1de
> Feature: Cancel all missions

- .github/workflows/mir_workflows.yml
- .github/workflows/otto_workflows.yml
- mir_connector/README.md
- mir_connector/inorbit_mir_connector/__init__.py
- mir_connector/inorbit_mir_connector/mir100_start.py
- mir_connector/setup.py
Fixed the following issues in the project documentation:
* Removed solved TODOs.
* Updated the authors list and project classifiers.
* Fixed references to branch names in workflows.
* Added workflow status badge to README.md.
* Removed no longer valid instructions for running the publish job locally with act (the job doesn't use API tokens anymore).
* Added links to documentation in comments.
Project in TestPyPi: https://test.pypi.org/project/inorbit-mir-connector/
> Update MiR package information and documentation

- README.md
Add a short description of the MiR Connector in the main README. In the future, as more connectors are added, the format could change to a table like the following:
| Connector                                                                                     | Location                                   |
| --------------------------------------------------------------------------------------------- | ------------------------------------------ |
| [OTTO Motors](https://directory.inorbit.ai/connect/OTTO-Motors)                               | [otto_connector](otto_connector/README.md) |
| [Mobile Industrial Robots](https://directory.inorbit.ai/connect/Mobile-Industrial-Robots-A/S) | [mir_connector](mir_connector/README.md)   |
> Add short description for the MiR Connector in the main README.md file

- instock_connector/CONTRIBUTING.md
- instock_connector/config/example.env
> [Instock Connector] Documentation fixes

- mir_connector/README.md
- mir_connector/config/my_fleet.example.yaml
- mir_connector/inorbit_mir_connector/config/mir100_model.py
- mir_connector/inorbit_mir_connector/src/connector.py
- mir_connector/inorbit_mir_connector/tests/test_config_validation.py
- mir_connector/inorbit_mir_connector/tests/test_connector.py
Add an option to disable the websockets interface on the MiR100 Connector.
> MiR100 Connector: Allow disabling the websockets interface

- gausium_connector/inorbit_gausium_connector/src/connector.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/test_connector.py
Implement initial pose and waypoint navigation commands
> Gausium Connector: Waypoint navigation and pose initialization

- gausium_connector/inorbit_gausium_connector/src/connector.py
- gausium_connector/inorbit_gausium_connector/tests/test_connector.py
Publish `robot_available` value.
> Gausium Connector: Publish `robot_available` value

- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_api.py
Calculate the orientation from the `angle` value returned by `/gs-robot/real_time_data/position`.
> Gausium Connector: Fix robot orientation

- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/conftest.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_api.py
Fetch real time robot status data and publish it as key-value pairs.
> Gausium Connector: Fetch `/gs-robot/real_time_data/robot_status` endpoint

- gausium_connector/cac_examples/ActionDefinition.yaml
- gausium_connector/config/example.yaml
- gausium_connector/inorbit_gausium_connector/src/connector.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/test_connector.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_api.py
Bug fixes that result from real-world testing.
* Improve error handling of failed requests that return code 200 but with a falsey "successed" value.
* Fix waypoint navigation, which is meant to be used with grid coordinates instead of the location in meters.
* Uncomment lines that fetched the map, which were accidentally merged in #49.
* Do not flatten published dictionaries, and recommend using JSON datasources.
* Execute API calls in `update()` concurrently.
* Fix firmware version number comparison.
* Fix format of start task queue requests
* Fix cancel task queue
> Gausium Connector: Various fixes

- gausium_connector/inorbit_gausium_connector/src/connector.py
- gausium_connector/inorbit_gausium_connector/src/robot/constants.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/conftest.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_api.py
Publish paths while:
* navigating to coordinates
* navigating to a waypoint
* executing a task
> Gausium Connector: Publish paths

- gausium_connector/inorbit_gausium_connector/inorbit_gausium_connector.py
- gausium_connector/inorbit_gausium_connector/src/connector.py
- gausium_connector/inorbit_gausium_connector/src/mission.py
- gausium_connector/inorbit_gausium_connector/src/robot/__init__.py
- gausium_connector/inorbit_gausium_connector/src/robot/datatypes.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_factory.py
- gausium_connector/inorbit_gausium_connector/src/robot/utils.py
- gausium_connector/inorbit_gausium_connector/tests/test_connector.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_factory.py
- gausium_connector/inorbit_gausium_connector/tests/test_utils.py
- gausium_connector/requirements-dev.txt
- gausium_connector/requirements.txt
* Upgrade to `inorbit-connector` v1, which supports `asyncio`.
* Refactor the API client to use `httpx` and async calls.
* Implement the pattern shown in framework's [example](https://github.com/inorbit-ai/inorbit-connector-python/tree/main/examples/robot-connector).
[TODO]
> Gausium Connector: Upgrade to `asyncio` based `inorbit-connector`

- gausium_connector/inorbit_gausium_connector/src/connector.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/test_connector.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_api.py
- gausium_connector/requirements.txt
Add a retry policy for API methods that may need to be retried.
> Gausium Connector: Retry policy for actions

- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
If the loglevel is INFO, reduce the verbosity of httpx logs, which result too verbose
> Gausium Connector: Reduce log spam

- .gitignore
- gausium_connector/config/example.yaml
- gausium_connector/inorbit_gausium_connector/src/config/connector_model.py
- gausium_connector/inorbit_gausium_connector/src/connector.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_api.py
- gausium_connector/inorbit_gausium_connector/src/robot/robot_factory.py
- gausium_connector/inorbit_gausium_connector/tests/test_config_validation.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_api.py
- gausium_connector/inorbit_gausium_connector/tests/test_robot_factory.py
- gausium_connector/requirements.txt
Upgraded to the latest versions of `inorbit-edge` and `inorbit-connector` and adapted the code and examples accordingly.
> Gausium connector: Upgrade `inorbit-edge` and `inorbit-connector` dependencies

- mir_connector/config/my_fleet.example.yaml
- mir_connector/inorbit_mir_connector/config/connector_model.py
- mir_connector/inorbit_mir_connector/src/connector.py
- mir_connector/inorbit_mir_connector/src/mir_api/__init__.py
- mir_connector/inorbit_mir_connector/src/mir_api/mir_api_base.py
- mir_connector/inorbit_mir_connector/src/mir_api/mir_api_v2.py
- mir_connector/inorbit_mir_connector/src/mission.py
- mir_connector/inorbit_mir_connector/tests/test_connector.py
- mir_connector/inorbit_mir_connector/tests/test_mir_api_v2.py
- mir_connector/inorbit_mir_connector/tests/test_mission_tracking.py
- mir_connector/setup.py
feat: Add comprehensive SSL configuration with hostname verification bypass
- Add ssl_ca_bundle support for custom CA certificates
- Add ssl_verify_hostname option for FRP/proxy/tunnel setups
- Support secure HTTPS with self-signed certificates
- Update configuration examples with 4 clear SSL scenarios
- Fix SSL transport handling for both async and sync operations
Enables secure connections through tunnels while maintaining certificate
verification, addressing common deployment scenarios with FRP and VPNs.
Fixes hostname mismatch errors when connecting through proxies.
> Comprehensive SSL configuration support

- mir_connector/inorbit_mir_connector/config/connector_model.py
- mir_connector/inorbit_mir_connector/src/mir_api/mir_api_base.py
- mir_connector/inorbit_mir_connector/src/mir_api/mir_api_v2.py
- mir_connector/inorbit_mir_connector/src/mission_exec.py
- mir_connector/inorbit_mir_connector/src/mission_tracking.py
- mir_connector/inorbit_mir_connector/tests/test_mir_api_v2.py
- mir_connector/inorbit_mir_connector/tests/test_mission_tracking.py
Fixed incorrect naming of `cancelMissionAction`
> Update `cancelMissionAction` script name

- mir_connector/inorbit_mir_connector/config/connector_model.py
- mir_connector/inorbit_mir_connector/inorbit_mir_connector.py
Improve error handling for config validation.
> Improve error handling for config validation

- mir_connector/config/my_fleet.example.yaml
- mir_connector/inorbit_mir_connector/config/connector_model.py
- mir_connector/inorbit_mir_connector/src/connector.py
- mir_connector/inorbit_mir_connector/src/mir_api/mir_api_v2.py
- mir_connector/inorbit_mir_connector/src/mir_api/missions_group.py
- Extract missions group handling from the Connector class
- Allow configuring its use, and using a built-in mission for waypoint navigation
> Waypoint navigation through built-in mission

- mir_connector/inorbit_mir_connector/src/connector.py
Fixes the map upload which incorrectly was setting origin y to origin x
> fixes the map origin when publishing

- mir_connector/.gitignore
- mir_connector/README.md
- mir_connector/config/example.env
- mir_connector/config/fleet.example.yaml
- mir_connector/config/fleet.simple.example.yaml
- mir_connector/docker/Dockerfile
- mir_connector/docker/docker-compose.example.yaml
- mir_connector/inorbit_mir_connector/src/connector.py
- mir_connector/inorbit_mir_connector/tests/test_connector.py
- mir_connector/setup.py
- Reorganize README with better flow
- Add Docker deployment as recommended production approach with clear benefits
- Add bare-metal deployment alternative with process supervision setup
- Create docker-compose.example.yaml template for users
- Modifies connector to register publish messages to better track connection status and connector health
> Restructure README and improve production deployment
